# Generated by Django 4.2.27 on 2025-12-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('content_migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migration_jobs', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='migrationplan',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migration_plans', to='core.tenant'),
        ),
    ]
