# Generated by Django 4.2.27 on 2025-12-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_migration', '0002_migrationjob_tenant_migrationplan_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationplan',
            name='query_dsl',
            field=models.TextField(blank=True, help_text='DSL or path for retrieving data from source'),
        ),
    ]
