# Generated by Django 4.2.24 on 2026-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_migration", "0003_migrationplan_query_dsl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migrationplan",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Migration configuration (batch_size, skip_existing, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="migrationplan",
            name="workflow",
            field=models.JSONField(blank=True, default=list, help_text="Sequence of steps to process each item"),
        ),
    ]
