# Generated by Django 4.2.23 on 2025-07-15 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webpages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageversion",
            name="change_summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Summary of specific changes made in this version",
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="When this version was published", null=True
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Current status of this version",
                max_length=20,
            ),
        ),
    ]
