# Generated by Django 4.2.23 on 2025-07-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "webpages",
            "0002_pageversion_change_summary_pageversion_published_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagewidget",
            options={"ordering": ["slot_name", "-priority", "sort_order"]},
        ),
        migrations.AddField(
            model_name="pagewidget",
            name="inheritance_behavior",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit from Parent"),
                    ("override", "Override Parent Widget"),
                    ("supplement", "Add to Parent Widgets"),
                    ("block", "Block Inheritance"),
                    ("conditional", "Conditional Inheritance"),
                ],
                default="inherit",
                help_text="How this widget handles inheritance",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pagewidget",
            name="inheritance_conditions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON conditions for when inheritance applies",
            ),
        ),
        migrations.AddField(
            model_name="pagewidget",
            name="is_visible",
            field=models.BooleanField(
                default=True, help_text="Whether this widget is visible on the page"
            ),
        ),
        migrations.AddField(
            model_name="pagewidget",
            name="max_inheritance_depth",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum depth this widget can be inherited (null = unlimited)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pagewidget",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Higher priority widgets appear first (0 = normal priority)",
            ),
        ),
    ]
