# Generated by Django 4.2.23 on 2025-07-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0003_alter_pagewidget_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpage",
            name="effective_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this page should become public",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="webpage",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this page should no longer be public",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="webpage",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("unpublished", "Unpublished"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="unpublished",
                max_length=20,
            ),
        ),
    ]
