# Generated by Django 4.2.23 on 2025-07-18 09:51

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0004_add_publishing_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="hostnames",
            field=models.JSONField(
                blank=True,
                null=True,
                help_text="List of hostnames this root page serves (only for pages without parent)",
            ),
        ),
        migrations.AddIndex(
            model_name="webpage",
            index=models.Index(fields=["slug"], name="webpages_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="webpage",
            index=models.Index(
                fields=["hostnames"], name="webpages_hostnames_idx"
            ),
        ),
    ]
