# Generated by Django 4.2.23 on 2025-07-18 09:51

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0004_add_publishing_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="hostnames",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="List of hostnames this root page serves (only for pages without parent)",
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="webpage",
            index=models.Index(fields=["slug"], name="webpages_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="webpage",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["hostnames"], name="webpages_hostnames_gin_idx"
            ),
        ),
    ]
