# Generated by Django 4.2.23 on 2025-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0005_add_hostnames_and_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagelayout",
            name="template_name",
            field=models.CharField(
                default="webpages/page_detail.html",
                help_text="Template file used to render this layout",
                max_length=255,
            ),
        ),
    ]
