# Generated by Django 4.2.23 on 2025-07-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0007_remove_pagewidget_add_version_widgets"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="code_layout",
            field=models.CharField(
                blank=True,
                help_text="Name of code-based layout class. Takes precedence over database layout. Leave blank to inherit from parent",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pageversion",
            name="page_data",
            field=models.JSONField(
                help_text="Serialized page data (excluding widgets)"
            ),
        ),
        migrations.AlterField(
            model_name="webpage",
            name="layout",
            field=models.ForeignKey(
                blank=True,
                help_text="Database layout (legacy). Leave blank to inherit from parent or use code_layout",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="webpages.pagelayout",
            ),
        ),
    ]
