# Generated by Django 4.2.23 on 2025-07-19 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0009_remove_pagelayout_model"),
    ]

    operations = [
        # Remove the WidgetType model - widget types are now code-based
        migrations.DeleteModel(
            name="WidgetType",
        ),
    ]
