# Generated by Django 4.2.23 on 2025-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0010_remove_widgettype_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpage",
            name="code_layout",
            field=models.CharField(
                blank=True,
                help_text="Name of code-based layout class. Leave blank to inherit from parent",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="webpage",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
