# Generated by Django 4.2.23 on 2025-07-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0011_remove_slug_uniqueness"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="webpage",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="webpage",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
