# Generated by Django 4.2.23 on 2025-07-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0013_add_css_injection_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageversion",
            name="widgets",
            field=models.JSONField(
                default=dict,
                help_text="Widget configuration data for this version (slot_name -> widgets array)",
            ),
        ),
    ]
