# Generated by Django 4.2.23 on 2025-08-01 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webpages", "0014_fix_widgets_default_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageversion",
            name="effective_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this version becomes live/published",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this version should no longer be live",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pageversion",
            name="is_current",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the currently active version (LEGACY)",
            ),
        ),
        migrations.AlterField(
            model_name="pageversion",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this version was published (LEGACY)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pageversion",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this version (LEGACY)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pageversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Current status of this version (LEGACY - use dates instead)",
                max_length=20,
            ),
        ),
    ]
