# Generated by Django 4.2.23 on 2025-08-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0016_migrate_publishing_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pageversion",
            name="is_current",
        ),
        migrations.RemoveField(
            model_name="pageversion",
            name="published_at",
        ),
        migrations.RemoveField(
            model_name="pageversion",
            name="published_by",
        ),
        migrations.RemoveField(
            model_name="pageversion",
            name="status",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="effective_date",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="publication_status",
        ),
    ]
