# Generated by Django 4.2.23 on 2025-08-07 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0019_remove_webpage_title_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webpage",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="linked_object_id",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="linked_object_type",
        ),
    ]
