# Generated by Django 4.2.23 on 2025-08-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0020_remove_linked_object_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pageversion",
            old_name="description",
            new_name="version_title",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="code_layout",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="enable_css_injection",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="page_css_variables",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="page_custom_css",
        ),
        migrations.RemoveField(
            model_name="webpage",
            name="theme",
        ),
        migrations.AddField(
            model_name="pageversion",
            name="code_layout",
            field=models.CharField(
                blank=True,
                help_text="Name of code-based layout class. Leave blank to inherit from parent",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="enable_css_injection",
            field=models.BooleanField(
                default=True,
                help_text="Whether to enable dynamic CSS injection for this page",
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="page_css_variables",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Page-specific CSS variables that override theme variables",
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="page_custom_css",
            field=models.TextField(
                blank=True,
                help_text="Page-specific custom CSS injected after theme CSS",
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to inherit from parent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="webpages.pagetheme",
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="title",
            field=models.TextField(blank=True, help_text="Page Title"),
        ),
    ]
