# Generated by Django 4.2.23 on 2025-08-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0021_rename_description_pageversion_version_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="webpage",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
