# Generated by Django 4.2.23 on 2025-08-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0022_webpage_description_webpage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="enable_css_injection",
            field=models.BooleanField(
                default=True,
                help_text="Whether to enable dynamic CSS injection for this page",
            ),
        ),
        migrations.AddField(
            model_name="webpage",
            name="page_css_variables",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Page-specific CSS variables that override theme variables",
            ),
        ),
        migrations.AddField(
            model_name="webpage",
            name="page_custom_css",
            field=models.TextField(
                blank=True,
                help_text="Page-specific custom CSS injected after theme CSS",
            ),
        ),
    ]
