# Generated by Django 4.2.23 on 2025-08-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0024_pagedataschema"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pagedataschema",
            name="unique_schema_per_scope_layout_name",
        ),
        migrations.AlterField(
            model_name="pagedataschema",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pagedataschema",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="pagedataschema",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("scope", "system")),
                fields=("scope",),
                name="unique_active_system_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagedataschema",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("scope", "layout")),
                fields=("scope", "layout_name"),
                name="unique_active_layout_schema",
            ),
        ),
    ]
