# Generated by Django 4.2.23 on 2025-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0025_update_schema_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageversion",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
