# Generated by Django 4.2.23 on 2025-08-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0026_pageversion_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pageversion",
            name="description",
        ),
        migrations.RemoveField(
            model_name="pageversion",
            name="title",
        ),
        migrations.AddField(
            model_name="pageversion",
            name="meta_description",
            field=models.TextField(
                blank=True, default="", help_text="Meta Description"
            ),
        ),
        migrations.AddField(
            model_name="pageversion",
            name="meta_title",
            field=models.TextField(blank=True, help_text="Meta Title"),
        ),
    ]
