# Generated by Django 4.2.23 on 2025-08-22 20:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0027_rename_pageversion_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageversion",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="List of tag names for organizing and categorizing page versions",
                size=None,
            ),
        ),
    ]
