# Generated by Django 4.2.23 on 2025-08-22 20:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0027_rename_pageversion_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageversion",
            name="tags",
            field=models.JSONField(
                blank=True,
                null=True,
                help_text="List of tag names for organizing and categorizing page versions",
            ),
        ),
    ]
