# Generated by Django 4.2.23 on 2025-09-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0028_add_tags_to_pageversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetheme",
            name="html_elements",
            field=models.JSONField(
                default=dict,
                help_text="JSON object defining styles for HTML elements (h1-h6, p, ul, ol, li, a, blockquote, code, pre, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="css_variables",
            field=models.JSONField(
                default=dict, help_text="JSON object with CSS custom properties"
            ),
        ),
    ]
