# Generated by Django 4.2.23 on 2025-09-07 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webpages", "0029_add_html_elements_to_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayoutThemeAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layout_name",
                    models.CharField(
                        help_text="Name of the code-based layout",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this association is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        help_text="Theme to associate with this layout (overrides code-based default)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webpages.pagetheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layout Theme Association",
                "verbose_name_plural": "Layout Theme Associations",
                "ordering": ["layout_name"],
            },
        ),
    ]
