# Generated by Django 4.2.23 on 2025-09-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0030_add_layout_theme_association"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetheme",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the default theme for object content editors",
            ),
        ),
        migrations.DeleteModel(
            name="LayoutThemeAssociation",
        ),
    ]
