# Generated by Django 4.2.23 on 2025-09-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0015_convert_widget_config_to_snake_case"),
        ("webpages", "0031_add_is_default_to_theme_remove_layout_associations"),
    ]

    operations = []
