# Generated by Django 4.2.23 on 2025-09-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0032_merge_20250912_1242"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetheme",
            name="image_styles",
            field=models.JSONField(
                default=dict,
                help_text="JSON object defining named image styles for widgets (alignment, columns, spacing, etc.)",
            ),
        ),
    ]
