# Generated by Django 4.2.23 on 2025-09-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0032_add_image_field_to_pagetheme"),
        ("webpages", "0033_add_image_styles_to_theme"),
    ]

    operations = []
