# Generated by Django 4.2.24 on 2025-10-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0034_merge_20250913_1334"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagetheme",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="webpage",
            name="path_pattern",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Regex pattern to capture path variables (e.g., ^(?P<news_slug>[\\w-]+)/$). Enables dynamic object publishing where widgets can access captured variables.",
                max_length=500,
            ),
        ),
    ]
