# Generated by Django 4.2.24 on 2025-10-10 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webpages", "0035_add_path_pattern_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="When this page was marked as deleted", null=True
            ),
        ),
        migrations.AddField(
            model_name="webpage",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this page",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webpage",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this page is marked as deleted (soft delete for reversibility)",
            ),
        ),
    ]
