# Generated by Django 4.2.23 on 2025-10-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0037_path_pattern_to_registry"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
