# Generated by Django 4.2.25 on 2025-10-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0038_pageversion_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviewSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this preview size (e.g., 'Desktop', 'iPhone 14')",
                        max_length=100,
                    ),
                ),
                ("width", models.IntegerField(help_text="Viewport width in pixels")),
                (
                    "height",
                    models.IntegerField(
                        blank=True,
                        help_text="Viewport height in pixels (optional for responsive heights)",
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Display order in UI (lower numbers first)"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Mark as a default/system preview size"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Preview Size",
                "verbose_name_plural": "Preview Sizes",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
