# Generated by Django 4.2.25 on 2025-10-22 08:44

from django.db import migrations


def populate_default_preview_sizes(apps, schema_editor):
    """Create default preview sizes based on common Tailwind breakpoints"""
    PreviewSize = apps.get_model("webpages", "PreviewSize")

    default_sizes = [
        {
            "name": "Desktop",
            "width": 1920,
            "height": 1080,
            "sort_order": 0,
            "is_default": True,
        },
        {
            "name": "Laptop",
            "width": 1280,
            "height": 800,
            "sort_order": 1,
            "is_default": True,
        },
        {
            "name": "Tablet",
            "width": 768,
            "height": 1024,
            "sort_order": 2,
            "is_default": True,
        },
        {
            "name": "Mobile Large",
            "width": 640,
            "height": 844,
            "sort_order": 3,
            "is_default": True,
        },
        {
            "name": "Mobile",
            "width": 375,
            "height": 667,
            "sort_order": 4,
            "is_default": True,
        },
    ]

    for size_data in default_sizes:
        PreviewSize.objects.create(**size_data)


def reverse_populate_default_preview_sizes(apps, schema_editor):
    """Remove default preview sizes"""
    PreviewSize = apps.get_model("webpages", "PreviewSize")
    PreviewSize.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0039_previewsize"),
    ]

    operations = [
        migrations.RunPython(
            populate_default_preview_sizes,
            reverse_populate_default_preview_sizes,
        ),
    ]
