# Generated by Django 4.2.25 on 2025-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0040_populate_default_preview_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="site_icon",
            field=models.ImageField(
                blank=True,
                help_text="Site icon/favicon for this root page. Will be resized to multiple sizes using imgproxy. Only available for root pages (pages without parent).",
                null=True,
                upload_to="site_icons/",
            ),
        ),
    ]
