# Generated by Django 4.2.25 on 2025-10-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0042_redesign_theme_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetheme",
            name="carousel_styles",
            field=models.JSONField(
                default=dict,
                help_text="Mustache templates for image carousel rendering with CSS and Alpine.js",
            ),
        ),
        migrations.AddField(
            model_name="pagetheme",
            name="gallery_styles",
            field=models.JSONField(
                default=dict,
                help_text="Mustache templates for image gallery rendering with CSS",
            ),
        ),
    ]
