# Generated by Django 4.2.25 on 2025-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0044_populate_default_theme_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='deletion_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata for restoring deleted pages (parent path, location, etc.)'),
        ),
    ]
