# Generated by Django 4.2.25 on 2025-10-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0045_add_deletion_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicatePageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='The slug that has duplicates', max_length=255)),
                ('page_ids', models.JSONField(help_text='List of page IDs that were found as duplicates')),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='When this duplicate was first detected')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Most recent time this duplicate was encountered')),
                ('occurrence_count', models.IntegerField(default=1, help_text='Number of times this duplicate has been encountered')),
                ('resolved', models.BooleanField(default=False, help_text='Whether this duplicate has been resolved (e.g., pages merged or deleted)')),
                ('email_sent', models.DateTimeField(blank=True, help_text='When an email notification was last sent about this duplicate', null=True)),
                ('notes', models.TextField(blank=True, help_text='Administrative notes about this duplicate')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent page where duplicates were found (null for root pages)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_logs', to='webpages.webpage')),
            ],
            options={
                'verbose_name': 'Duplicate Page Log',
                'verbose_name_plural': 'Duplicate Page Logs',
                'db_table': 'webpages_duplicate_page_log',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['slug', 'parent'], name='webpages_du_slug_d767a1_idx'), models.Index(fields=['resolved', '-last_seen'], name='webpages_du_resolve_08611a_idx'), models.Index(fields=['-email_sent'], name='webpages_du_email_s_9bae8f_idx')],
            },
        ),
    ]
