# Generated by Django 4.2.25 on 2025-10-30 13:40

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0049_webpage_cached_root_hostnames_webpage_cached_root_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webpage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cached_root_hostnames'], name='webpages_root_hosts_gin'),
        ),
    ]
