# Generated by Django 4.2.25 on 2025-11-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0050_webpage_webpages_root_hosts_gin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagetheme',
            old_name='typography',
            new_name='design_groups',
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='design_groups',
            field=models.JSONField(
                default=dict,
                help_text='Grouped HTML element styles with color schemes and optional widget_type/slot targeting',
            ),
        ),
    ]
