# Generated by Django 4.2.25 on 2025-11-10 15:25

from django.db import migrations


def migrate_to_unified_image_styles(apps, schema_editor):
    """
    Migrate existing gallery_styles and carousel_styles to unified image_styles.
    Adds styleType field to each style.
    """
    PageTheme = apps.get_model('webpages', 'PageTheme')
    
    for theme in PageTheme.objects.all():
        image_styles = theme.image_styles or {}
        
        # Migrate gallery_styles
        if theme.gallery_styles:
            for key, style in theme.gallery_styles.items():
                if key not in image_styles:
                    image_styles[key] = {**style, "styleType": "gallery"}
        
        # Migrate carousel_styles
        if theme.carousel_styles:
            for key, style in theme.carousel_styles.items():
                if key not in image_styles:
                    image_styles[key] = {**style, "styleType": "carousel"}
        
        # Save the unified image_styles
        if image_styles:
            theme.image_styles = image_styles
            theme.save(update_fields=['image_styles'])


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: split image_styles back to gallery_styles and carousel_styles
    """
    PageTheme = apps.get_model('webpages', 'PageTheme')
    
    for theme in PageTheme.objects.all():
        if not theme.image_styles:
            continue
        
        gallery_styles = {}
        carousel_styles = {}
        
        for key, style in theme.image_styles.items():
            style_copy = {k: v for k, v in style.items() if k != "styleType"}
            style_type = style.get("styleType", "gallery")
            
            if style_type == "carousel":
                carousel_styles[key] = style_copy
            else:
                gallery_styles[key] = style_copy
        
        theme.gallery_styles = gallery_styles
        theme.carousel_styles = carousel_styles
        theme.save(update_fields=['gallery_styles', 'carousel_styles'])


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0051_rename_typography_to_design_groups'),
    ]

    operations = [
        migrations.RunPython(migrate_to_unified_image_styles, reverse_migration),
    ]
