# Generated by Django 4.2.25 on 2025-11-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0052_migrate_to_unified_image_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetheme',
            name='breakpoints',
            field=models.JSONField(default=dict, help_text="Responsive breakpoint configuration with pixel values for media queries. Format: {'sm': 640, 'md': 768, 'lg': 1024, 'xl': 1280}. If not specified, defaults to standard breakpoints."),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='carousel_styles',
            field=models.JSONField(default=dict, help_text="DEPRECATED: Use 'image_styles' field instead"),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='design_groups',
            field=models.JSONField(default=dict, help_text="Grouped HTML element styles with optional widget_type/slot targeting. Each group can have an 'isDefault' boolean field to mark it as the base/default group for style inheritance. Groups can also include 'layoutProperties' to define responsive layout and styling settings (width, height, padding, margin, gap, background-color, color, border properties, etc.) for widget layout parts (e.g., container, header, image, content) across breakpoints (desktop, tablet, mobile)."),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='gallery_styles',
            field=models.JSONField(default=dict, help_text="DEPRECATED: Use 'image_styles' field instead"),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='html_elements',
            field=models.JSONField(default=dict, help_text="DEPRECATED: Use 'design_groups' field instead"),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='image',
            field=models.ImageField(blank=True, help_text="Theme preview image for listings and selection. Note: Files uploaded to theme_images/ should have public-read ACL in object storage for direct browser access. Set AWS_DEFAULT_ACL='public-read' in production settings or configure bucket policy to allow public read access to theme_images/* objects.", null=True, upload_to='theme_images/'),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='image_styles',
            field=models.JSONField(default=dict, help_text='Unified image styles (gallery and carousel) with Mustache templates and CSS. Each style supports: template (required), styleType (gallery|carousel, required), css, variables, imgproxy_config, lightbox_config, enableLightbox (boolean), lightboxTemplate (string), defaultShowCaptions (boolean), defaultLightboxGroup (string), defaultRandomize (boolean). Carousel styles also support: defaultAutoPlay (boolean), defaultAutoPlayInterval (number 1-30).'),
        ),
    ]
