# Generated by Django 4.2.26 on 2025-12-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0054_ensure_image_styles_have_styletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetheme',
            name='design_groups',
            field=models.JSONField(default=dict, help_text="Grouped HTML element styles with optional widget_type/slot targeting. Each group can have an 'isDefault' boolean field to mark it as the base/default group for style inheritance. Groups can also include 'layoutProperties' to define responsive layout and styling settings (width, height, padding, margin, gap, background-color, color, border properties, etc.) for widget layout parts (e.g., container, header, image, content) across mobile-first breakpoints (sm, md, lg, xl)."),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='image_styles',
            field=models.JSONField(default=dict, help_text="Unified image styles (gallery and carousel) with Mustache templates and CSS. Each style supports: template (required), styleType (gallery|carousel, required), usageType (standard|inline|both, defaults to 'both'), css, variables, imgproxy_config, lightbox_config, enableLightbox (boolean), lightboxTemplate (string), defaultShowCaptions (boolean), defaultLightboxGroup (string), defaultRandomize (boolean). Carousel styles also support: defaultAutoPlay (boolean), defaultAutoPlayInterval (number 1-30)."),
        ),
    ]
