# Generated by Django 4.2.26 on 2025-12-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0055_alter_pagetheme_design_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetheme',
            name='design_groups',
            field=models.JSONField(default=dict, help_text="Grouped HTML element styles with optional widget_type/slot targeting. Each group can have an 'isDefault' boolean field to mark it as the base/default group for style inheritance. Groups can also include 'layoutProperties' to define responsive layout and styling settings (width, height, padding, margin, gap, background-color, color, border properties, etc.) for widget layout parts (e.g., container, header, image, content) across mobile-first breakpoints (sm, md, lg, xl). Supports two targeting modes via 'targetingMode' field: 'widget-slot' (default) for widget_types/slots arrays, or 'css-classes' for custom CSS selectors defined in 'targetCssClasses' field (string with comma or newline-separated selectors)."),
        ),
    ]
