# Generated by Django 4.2.26 on 2025-12-15 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('webpages', '0059_add_theme_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetheme',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this theme belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='pagetheme',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='pagetheme',
            index=models.Index(fields=['tenant_id'], name='pagetheme_tenant_idx'),
        ),
    ]
