# Generated by Django 4.2.26 on 2025-12-15 18:55

from django.db import migrations
from django.contrib.auth.models import User


def create_default_tenant_and_assign_themes(apps, schema_editor):
    """Create a default tenant and assign all existing themes to it."""
    Tenant = apps.get_model('core', 'Tenant')
    PageTheme = apps.get_model('webpages', 'PageTheme')
    
    # Get or create default tenant
    default_tenant, created = Tenant.objects.get_or_create(
        identifier='default',
        defaults={
            'name': 'Default Tenant',
            'is_active': True,
            'created_by_id': User.objects.filter(is_superuser=True).first().id if User.objects.filter(is_superuser=True).exists() else User.objects.first().id if User.objects.exists() else None,
        }
    )
    
    if created:
        print(f"Created default tenant: {default_tenant.name} (identifier: {default_tenant.identifier})")
    else:
        print(f"Using existing default tenant: {default_tenant.name} (identifier: {default_tenant.identifier})")
    
    # Assign all themes without a tenant to the default tenant
    themes_without_tenant = PageTheme.objects.filter(tenant__isnull=True)
    count = themes_without_tenant.update(tenant=default_tenant)
    print(f"Assigned {count} themes to default tenant")


def reverse_migration(apps, schema_editor):
    """Reverse migration - set tenant to None for all themes."""
    PageTheme = apps.get_model('webpages', 'PageTheme')
    PageTheme.objects.all().update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('webpages', '0060_pagetheme_tenant_alter_pagetheme_name_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_tenant_and_assign_themes, reverse_migration),
    ]
