# Generated by Django 4.2.26 on 2025-12-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('webpages', '0061_assign_themes_to_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetheme',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this theme belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='themes',
                to='core.tenant'
            ),
        ),
    ]
