# Generated by Django 4.2.26 on 2025-12-15 19:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('webpages', '0062_make_tenant_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                help_text='Tenant this page belongs to',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='webpages',
                to='core.tenant',
                db_column='tenant_id',
            ),
        ),
        migrations.AddIndex(
            model_name='webpage',
            index=models.Index(fields=['tenant_id'], name='webpages_tenant_idx'),
        ),
    ]
