# Generated by Django 4.2.26 on 2025-12-15 19:56

from django.db import migrations
from django.contrib.auth.models import User


def assign_pages_to_default_tenant(apps, schema_editor):
    """Assign all existing pages to the default tenant."""
    from django.db import connection
    import uuid
    
    Tenant = apps.get_model('core', 'Tenant')
    WebPage = apps.get_model('webpages', 'WebPage')
    
    # Get or create default tenant
    default_tenant, created = Tenant.objects.get_or_create(
        identifier='default',
        defaults={
            'name': 'Default Tenant',
            'is_active': True,
            'created_by_id': User.objects.filter(is_superuser=True).first().id if User.objects.filter(is_superuser=True).exists() else User.objects.first().id if User.objects.exists() else None,
        }
    )
    
    if created:
        print(f"Created default tenant: {default_tenant.name} (identifier: {default_tenant.identifier})")
    else:
        print(f"Using existing default tenant: {default_tenant.name} (identifier: {default_tenant.identifier})")
    
    # Assign all pages without a tenant to the default tenant
    # Use raw SQL to ensure UUID is handled correctly
    with connection.cursor() as cursor:
        # Get tenant UUID as string
        tenant_uuid = str(default_tenant.id) if isinstance(default_tenant.id, uuid.UUID) else default_tenant.id
        
        # Update pages using raw SQL to ensure UUID type
        cursor.execute(
            "UPDATE webpages_webpage SET tenant_id = %s::uuid WHERE tenant_id IS NULL",
            [tenant_uuid]
        )
        count = cursor.rowcount
    
    print(f"Assigned {count} pages to default tenant")


def reverse_migration(apps, schema_editor):
    """Reverse migration - set tenant to None for all pages."""
    WebPage = apps.get_model('webpages', 'WebPage')
    WebPage.objects.all().update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_tenant_to_webpage'),
        ('webpages', '0063_add_tenant_to_webpage'),
    ]

    operations = [
        migrations.RunPython(assign_pages_to_default_tenant, reverse_migration),
    ]

