# Generated by Django 4.2.26 on 2025-12-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0064_assign_pages_to_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this page belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='webpages',
                to='core.tenant',
            ),
        ),
    ]
