# Generated by Django 4.2.30 on 2026-04-13 21:28

from django.db import migrations, models
import file_manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0065_make_tenant_required_on_webpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetheme',
            name='image',
            field=models.ImageField(blank=True, help_text="Theme preview image for listings and selection. Note: Files uploaded to theme_images/ should have public-read ACL in object storage for direct browser access. Set AWS_DEFAULT_ACL='public-read' in production settings or configure bucket policy to allow public read access to theme_images/* objects.", null=True, storage=file_manager.storage.S3SystemStorage(), upload_to='theme_images/'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='site_icon',
            field=models.ImageField(blank=True, help_text='Site icon/favicon for this root page. Will be resized to multiple sizes using imgproxy. Only available for root pages (pages without parent).', null=True, storage=file_manager.storage.S3SystemStorage(), upload_to='site_icons/'),
        ),
    ]
