# Generated by Django 4.2.24 on 2026-04-13 14:52

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import file_manager.storage


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0065_make_tenant_required_on_webpage"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="webpage",
            name="webpages_hostnames_idx",
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Theme preview image for listings and selection. Note: Files uploaded to theme_images/ should have public-read ACL in object storage for direct browser access. Set AWS_DEFAULT_ACL='public-read' in production settings or configure bucket policy to allow public read access to theme_images/* objects.",
                null=True,
                storage=file_manager.storage.S3SystemStorage(),
                upload_to="theme_images/",
            ),
        ),
        migrations.AlterField(
            model_name="pageversion",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="List of tag names for organizing and categorizing page versions",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="webpage",
            name="cached_root_hostnames",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="Cached: Hostnames from root page (auto-maintained via signals)",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="webpage",
            name="hostnames",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="List of hostnames this root page serves (only for pages without parent)",
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="webpage",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["hostnames"], name="webpages_hostnames_gin_idx"
            ),
        ),
    ]
