# Generated by Django 4.2.30 on 2026-04-13 14:58

from django.db import migrations, models
import file_manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0066_remove_webpage_webpages_hostnames_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='site_icon',
            field=models.ImageField(blank=True, help_text='Site icon/favicon for this root page. Will be resized to multiple sizes using imgproxy. Only available for root pages (pages without parent).', null=True, storage=file_manager.storage.S3SystemStorage(), upload_to='site_icons/'),
        ),
    ]
