# Generated by Django 4.2.24 on 2026-04-13 21:50

from django.db import migrations, models
import file_manager.storage

def migrate_site_icons(apps, schema_editor):
    WebPage = apps.get_model("webpages", "WebPage")
    PageTheme = apps.get_model("webpages", "PageTheme")
    PageVersion = apps.get_model("webpages", "PageVersion")
    
    # Find all root pages with site_icons
    root_pages = WebPage.objects.filter(parent__isnull=True).exclude(models.Q(site_icon__isnull=True) | models.Q(site_icon=""))
    
    for page in root_pages:
        # Get the effective theme for this page
        # We need to check PageVersion for the theme assignment
        latest_version = PageVersion.objects.filter(page=page).order_by("-version_number").first()
        
        theme = None
        if latest_version and latest_version.theme:
            theme = latest_version.theme
        
        if not theme:
            # If no theme assigned, try to find the default theme
            theme = PageTheme.objects.filter(is_default=True).first()
            
        if theme and (not theme.site_icon or theme.site_icon == ""):
            # Copy the site_icon to the theme
            theme.site_icon = page.site_icon
            theme.save()

class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0066_alter_pagetheme_image_alter_webpage_site_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetheme",
            name="site_icon",
            field=models.ImageField(
                blank=True,
                help_text="Site icon/favicon for this theme. Will be resized to multiple sizes using imgproxy.",
                null=True,
                storage=file_manager.storage.S3SystemStorage(),
                upload_to="site_icons/",
            ),
        ),
        migrations.RunPython(migrate_site_icons, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="webpage",
            name="site_icon",
        ),
    ]
