# Generated by Django 4.2.24 on 2026-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0067_remove_webpage_site_icon_pagetheme_site_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagetheme",
            name="breakpoints",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Responsive breakpoint configuration with pixel values for media queries. Format: {'sm': 640, 'md': 768, 'lg': 1024, 'xl': 1280}. If not specified, defaults to standard breakpoints.",
            ),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="carousel_styles",
            field=models.JSONField(blank=True, default=dict, help_text="DEPRECATED: Use 'image_styles' field instead"),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="colors",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Named color palette (key-value pairs of color names and hex/rgb values)",
            ),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="component_styles",
            field=models.JSONField(
                blank=True, default=dict, help_text="Named component styles with HTML templates and optional CSS"
            ),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="css_variables",
            field=models.JSONField(blank=True, default=dict, help_text="DEPRECATED: Use 'colors' field instead"),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="design_groups",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Grouped HTML element styles with optional widget_type/slot targeting. Each group can have an 'isDefault' boolean field to mark it as the base/default group for style inheritance. Groups can also include 'layoutProperties' to define responsive layout and styling settings (width, height, padding, margin, gap, background-color, color, border properties, etc.) for widget layout parts (e.g., container, header, image, content) across mobile-first breakpoints (sm, md, lg, xl). Supports two targeting modes via 'targetingMode' field: 'widget-slot' (default) for widget_types/slots arrays, or 'css-classes' for custom CSS selectors defined in 'targetCssClasses' field (string with comma or newline-separated selectors).",
            ),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="fonts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Google Fonts configuration with family, variants, and display settings",
            ),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="gallery_styles",
            field=models.JSONField(blank=True, default=dict, help_text="DEPRECATED: Use 'image_styles' field instead"),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="html_elements",
            field=models.JSONField(blank=True, default=dict, help_text="DEPRECATED: Use 'design_groups' field instead"),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="image_styles",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Unified image styles (gallery and carousel) with Mustache templates and CSS. Each style supports: template (required), styleType (gallery|carousel, required), usageType (standard|inline|both, defaults to 'both'), css, variables, imgproxy_config, lightbox_config, enableLightbox (boolean), lightboxTemplate (string), defaultShowCaptions (boolean), defaultLightboxGroup (string), defaultRandomize (boolean). Carousel styles also support: defaultAutoPlay (boolean), defaultAutoPlayInterval (number 1-30).",
            ),
        ),
        migrations.AlterField(
            model_name="pagetheme",
            name="table_templates",
            field=models.JSONField(
                blank=True, default=dict, help_text="Predefined table templates for the Table widget"
            ),
        ),
        migrations.AlterField(
            model_name="pageversion",
            name="page_data",
            field=models.JSONField(blank=True, default=dict, help_text="Serialized page data (excluding widgets)"),
        ),
        migrations.AlterField(
            model_name="pageversion",
            name="widgets",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Widget configuration data for this version (slot_name -> widgets array)",
            ),
        ),
    ]
