# Generated by Django 4.2.24 on 2026-09-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('webpages', '0071_pagetheme_designer_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVersionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('page_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_tag_links', to='webpages.pageversion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_version_links', to='taxonomy.tag')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='pageversion',
            name='canonical_tags',
            field=models.ManyToManyField(blank=True, related_name='page_versions', through='webpages.PageVersionTag', to='taxonomy.tag'),
        ),
        migrations.AddConstraint(
            model_name='pageversiontag',
            constraint=models.UniqueConstraint(fields=('page_version', 'position'), name='webpages_version_tag_position_uniq'),
        ),
    ]
