# Generated by Django 4.2.30 on 2026-09-26 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashlib
import json
import uuid

SNAPSHOT_FIELDS = (
    "name",
    "description",
    "image",
    "site_icon",
    "fonts",
    "colors",
    "design_groups",
    "component_styles",
    "designer_preview",
    "image_styles",
    "gallery_styles",
    "carousel_styles",
    "table_templates",
    "breakpoints",
    "css_variables",
    "html_elements",
    "custom_css",
    "is_active",
    "is_default",
)


def create_initial_versions(apps, schema_editor):
    PageTheme = apps.get_model("webpages", "PageTheme")
    ThemeVersion = apps.get_model("webpages", "ThemeVersion")
    for theme in PageTheme.objects.all().iterator():
        snapshot = {
            field: (getattr(theme, field).name or None) if field in {"image", "site_icon"} else getattr(theme, field)
            for field in SNAPSHOT_FIELDS
        }
        encoded = json.dumps(snapshot, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
        ThemeVersion.objects.create(
            theme=theme,
            version_number=1,
            sync_version=theme.sync_version,
            snapshot=snapshot,
            content_hash=hashlib.sha256(encoded).hexdigest(),
            source="migration",
            source_label="Initial version",
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webpages", "0072_pageversiontag_pageversion_canonical_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetheme",
            name="stable_key",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name="ThemeVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.PositiveIntegerField()),
                ("sync_version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("source", models.CharField(default="web", max_length=32)),
                ("source_label", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_theme_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="webpages.pagetheme"
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="themeversion",
            constraint=models.UniqueConstraint(fields=("theme", "version_number"), name="unique_theme_version_number"),
        ),
        migrations.RunPython(create_initial_versions, migrations.RunPython.noop),
    ]
