# Generated by Django 4.2.30 on 2026-09-26 08:35

from django.db import migrations, models
import uuid


def make_lineage_keys_unique(apps, schema_editor):
    PageTheme = apps.get_model("webpages", "PageTheme")
    seen = set()
    for theme in PageTheme.objects.order_by("tenant_id", "id").iterator():
        key = (theme.tenant_id, theme.stable_key)
        if key in seen:
            theme.stable_key = uuid.uuid4()
            theme.save(update_fields=["stable_key"])
            key = (theme.tenant_id, theme.stable_key)
        seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0073_theme_version_history"),
    ]

    operations = [
        migrations.RunPython(make_lineage_keys_unique, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="pagetheme",
            constraint=models.UniqueConstraint(fields=("tenant", "stable_key"), name="unique_theme_lineage_per_tenant"),
        ),
    ]
