# Generated by Django 4.2.23 on 2025-07-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_create_default_namespace"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for this category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="content.namespace",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for this content object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_objects",
                to="content.namespace",
            ),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for this content object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_objects",
                to="content.namespace",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for this content object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_objects",
                to="content.namespace",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for this content object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_objects",
                to="content.namespace",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for this tag",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="content.namespace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("namespace", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("namespace", "slug")},
        ),
    ]
