# Generated by Django 4.2.23 on 2025-07-23 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_alter_event_namespace_alter_libraryitem_namespace_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for this content object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_objects",
                to="content.namespace",
            ),
        ),
        migrations.AlterField(
            model_name="libraryitem",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for this content object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_objects",
                to="content.namespace",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for this content object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_objects",
                to="content.namespace",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for this content object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_objects",
                to="content.namespace",
            ),
        ),
    ]
