# Generated by Django 4.2.23 on 2025-08-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_event_namespace_alter_libraryitem_namespace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#3B82F6",
                help_text="Hex color code for visual organization",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of what this tag represents"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is a system-generated tag (e.g., from AI)",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time this tag was used", null=True
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="usage_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this tag has been used"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["namespace", "name"], name="content_tag_ns_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["usage_count"], name="content_tag_usage_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["created_at"], name="content_tag_created_idx"),
        ),
    ]
