# Generated by Django 4.2.23 on 2025-08-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_tag_color_tag_description_tag_is_system_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("namespace", "name")},
        ),
        migrations.RemoveField(
            model_name="tag",
            name="color",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="is_system",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="last_used_at",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="updated_at",
        ),
    ]
