# Generated by Django 4.2.23 on 2025-08-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_remove_tag_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(default="djangodbmodelsfieldscharfield"),
        ),
    ]
