# Generated by Django 4.2.23 on 2025-08-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(),
        ),
    ]
