# Generated by Django 4.2.23 on 2025-08-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
