# Generated by Django 4.2.23 on 2025-08-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_alter_tag_name_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namespace",
            name="slug",
            field=models.SlugField(
                help_text="URL-safe namespace identifier", max_length=100, unique=True
            ),
        ),
    ]
