# Generated by Django 4.2.24 on 2025-10-12 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_alter_namespace_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libraryitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="libraryitem",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="libraryitem",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="libraryitem",
            name="namespace",
        ),
        migrations.RemoveField(
            model_name="libraryitem",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="member",
            name="category",
        ),
        migrations.RemoveField(
            model_name="member",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="member",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="member",
            name="namespace",
        ),
        migrations.RemoveField(
            model_name="member",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="news",
            name="category",
        ),
        migrations.RemoveField(
            model_name="news",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="news",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="news",
            name="namespace",
        ),
        migrations.RemoveField(
            model_name="news",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="LibraryItem",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="News",
        ),
    ]
