# Generated by Django 4.2.26 on 2025-12-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('content', '0017_remove_all_deprecated_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='namespace',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this namespace belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this tag belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.tenant'),
        ),
    ]
