# Generated by Django 4.2.26 on 2025-12-15 19:58

from django.db import migrations
from django.contrib.auth.models import User


def assign_content_to_default_tenant(apps, schema_editor):
    """Assign all existing content models to the default tenant."""
    from django.db import connection
    import uuid
    
    Tenant = apps.get_model('core', 'Tenant')
    Namespace = apps.get_model('content', 'Namespace')
    Category = apps.get_model('content', 'Category')
    Tag = apps.get_model('content', 'Tag')
    
    # Get or create default tenant
    default_tenant, created = Tenant.objects.get_or_create(
        identifier='default',
        defaults={
            'name': 'Default Tenant',
            'is_active': True,
            'created_by_id': User.objects.filter(is_superuser=True).first().id if User.objects.filter(is_superuser=True).exists() else User.objects.first().id if User.objects.exists() else None,
        }
    )
    
    if created:
        print(f"Created default tenant: {default_tenant.name} (identifier: {default_tenant.identifier})")
    else:
        print(f"Using existing default tenant: {default_tenant.name} (identifier: {default_tenant.identifier})")
    
    # Get tenant UUID as string
    tenant_uuid = str(default_tenant.id) if isinstance(default_tenant.id, uuid.UUID) else default_tenant.id
    
    # Assign all content models without a tenant to the default tenant
    Namespace.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    Category.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    Tag.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    
    print("Assigned content models to default tenant")


def reverse_migration(apps, schema_editor):
    """Reverse migration - set tenant to None for all content models."""
    Namespace = apps.get_model('content', 'Namespace')
    Category = apps.get_model('content', 'Category')
    Tag = apps.get_model('content', 'Tag')
    
    Namespace.objects.all().update(tenant=None)
    Category.objects.all().update(tenant=None)
    Tag.objects.all().update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('content', '0018_add_tenant_to_content_models'),
    ]

    operations = [
        migrations.RunPython(assign_content_to_default_tenant, reverse_migration),
    ]

