# Generated by Django 4.2.26 on 2025-12-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_assign_content_to_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this namespace belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='namespaces',
                to='core.tenant',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this category belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='categories',
                to='core.tenant',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this tag belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to='core.tenant',
            ),
        ),
    ]

