# Generated by Django 4.2.23 on 2025-09-13 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValueList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this value list",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label for this value list", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Auto-generated slug from label",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this value list represents",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                        ],
                        default="string",
                        help_text="Type of values stored in this list",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this value list is active and available for use",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a system-managed value list",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_value_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Value List",
                "verbose_name_plural": "Value Lists",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="ValueListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label for this item", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Auto-generated slug from label", max_length=100
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom value (defaults to slug if empty)",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description for this item"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order within the value list"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is active and available for selection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="utils.valuelist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Value List Item",
                "verbose_name_plural": "Value List Items",
                "ordering": ["order", "label"],
                "unique_together": {("value_list", "label"), ("value_list", "slug")},
            },
        ),
    ]
