# Generated by Django 4.2.23 on 2025-09-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="valuelist",
            options={
                "ordering": ["name"],
                "verbose_name": "Value List",
                "verbose_name_plural": "Value Lists",
            },
        ),
        migrations.RemoveField(
            model_name="valuelist",
            name="label",
        ),
        migrations.AlterField(
            model_name="valuelist",
            name="name",
            field=models.CharField(
                help_text="Name for this value list (used as both identifier and display label)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="valuelist",
            name="slug",
            field=models.SlugField(
                help_text="Auto-generated slug from name", max_length=100, unique=True
            ),
        ),
    ]
