# Generated by Django 4.2.24 on 2025-09-13 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("utils", "0002_remove_label_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAgentTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Human-readable task title", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed task description"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("summary", "Content Summarization"),
                            ("research", "Research & Analysis"),
                            ("content_generation", "Content Generation"),
                            ("data_analysis", "Data Analysis"),
                            ("custom", "Custom Task"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "task_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration parameters for the AI agent task",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Task results and generated content",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if task failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for monitoring",
                        max_length=255,
                    ),
                ),
                (
                    "estimated_duration",
                    models.DurationField(
                        blank=True,
                        help_text="Estimated task completion time",
                        null=True,
                    ),
                ),
                (
                    "actual_duration",
                    models.DurationField(
                        blank=True, help_text="Actual time taken to complete", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who initiated the task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAgentTaskTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("summary", "Content Summarization"),
                            ("research", "Research & Analysis"),
                            ("content_generation", "Content Generation"),
                            ("data_analysis", "Data Analysis"),
                            ("custom", "Custom Task"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_config",
                    models.JSONField(
                        default=dict,
                        help_text="Default configuration for tasks created from this template",
                    ),
                ),
                (
                    "config_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON schema for validating and generating UI forms",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_task_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIAgentTaskUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("progress", "Progress Update"),
                            ("status", "Status Change"),
                            ("result", "Partial Result"),
                            ("error", "Error/Warning"),
                            ("info", "Information"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Human-readable update message"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data for the update",
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Progress at time of update (0-100)",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="utils.aiagenttask",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["task", "timestamp"],
                        name="utils_aiage_task_id_297d3f_idx",
                    ),
                    models.Index(
                        fields=["update_type", "timestamp"],
                        name="utils_aiage_update__5b170e_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aiagenttask",
            index=models.Index(
                fields=["status", "created_at"], name="utils_aiage_status_f5c647_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiagenttask",
            index=models.Index(
                fields=["created_by", "status"], name="utils_aiage_created_bb5941_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiagenttask",
            index=models.Index(
                fields=["task_type", "status"], name="utils_aiage_task_ty_563700_idx"
            ),
        ),
    ]
