# Generated by Django 4.2.25 on 2025-11-20 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0003_create_ai_agent_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clipboard_type', models.CharField(choices=[('widgets', 'Widgets'), ('pages', 'Pages'), ('content', 'Content'), ('media', 'Media')], help_text='Type of clipboard content (widgets, pages, content, etc.)', max_length=20)),
                ('operation', models.CharField(choices=[('cut', 'Cut'), ('copy', 'Copy')], help_text='Operation type: cut or copy', max_length=10)),
                ('data', models.JSONField(default=dict, help_text='Clipboard content data (widgets, pages, etc.)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Operation-specific metadata (pageId, widgetPaths, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time for automatic cleanup', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this clipboard entry', on_delete=django.db.models.deletion.CASCADE, related_name='clipboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clipboard Entry',
                'verbose_name_plural': 'Clipboard Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'clipboard_type'], name='utils_clipb_user_id_24fb7e_idx'), models.Index(fields=['user', 'created_at'], name='utils_clipb_user_id_18cdf4_idx'), models.Index(fields=['clipboard_type', 'created_at'], name='utils_clipb_clipboa_929b4b_idx')],
            },
        ),
    ]
