# Generated by Django 4.2.24 on 2026-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0004_add_clipboard_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiagenttask",
            name="task_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Configuration parameters for the AI agent task"
            ),
        ),
        migrations.AlterField(
            model_name="aiagenttasktemplate",
            name="config_schema",
            field=models.JSONField(
                blank=True, default=dict, help_text="JSON schema for validating and generating UI forms"
            ),
        ),
        migrations.AlterField(
            model_name="aiagenttasktemplate",
            name="default_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Default configuration for tasks created from this template"
            ),
        ),
        migrations.AlterField(
            model_name="clipboardentry",
            name="data",
            field=models.JSONField(blank=True, default=dict, help_text="Clipboard content data (widgets, pages, etc.)"),
        ),
    ]
