# Generated by Django 4.2.24 on 2026-09-25 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_tenant_members'),
        ('content', '0021_reset_namespace_id_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBackfillRun',
            fields=[
                ('run_id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('source_fingerprint', models.CharField(max_length=71)),
                ('config_fingerprint', models.CharField(max_length=71)),
                ('code_revision', models.CharField(max_length=128)),
                ('total_work_units', models.PositiveIntegerField(default=0)),
                ('completed_work_units', models.PositiveIntegerField(default=0)),
                ('failed_work_units', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('interrupted', 'Interrupted'), ('failed', 'Failed'), ('complete', 'Complete')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('tag_type', models.SlugField(default='general', max_length=32)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_taxonomy_tags', to=settings.AUTH_USER_MODEL)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_tags', to='content.namespace')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_tags', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegacyTagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('content', 'Content tag'), ('media', 'Media tag')], max_length=16)),
                ('source_id', models.CharField(max_length=64)),
                ('source_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_mappings', to='taxonomy.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagBackfillUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_unit_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('failed', 'Failed')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='taxonomy.tagbackfillrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'status'], name='taxonomy_run_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tagbackfillunit',
            constraint=models.UniqueConstraint(fields=('run', 'work_unit_id'), name='taxonomy_backfill_unit_uniq'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tenant', 'namespace', 'tag_type', 'name'], name='taxonomy_tag_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tenant', 'namespace', 'tag_type', 'slug'), name='taxonomy_tag_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(check=models.Q(('namespace__isnull', False)), name='taxonomy_tag_namespace_required'),
        ),
        migrations.AddConstraint(
            model_name='legacytagmapping',
            constraint=models.UniqueConstraint(fields=('source_kind', 'source_id'), name='taxonomy_legacy_source_uniq'),
        ),
    ]
