# Generated by Django 4.2.23 on 2025-08-29 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="objectinstance",
            name="object_stor_parent__aead78_idx",
        ),
        migrations.RemoveField(
            model_name="objectinstance",
            name="parent_object",
        ),
        migrations.AddField(
            model_name="objectinstance",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objectinstance",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objectinstance",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Parent object for hierarchical relationships",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="object_storage.objectinstance",
            ),
        ),
        migrations.AddField(
            model_name="objectinstance",
            name="rght",
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objectinstance",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="objectinstance",
            index=models.Index(
                fields=["parent"], name="object_stor_parent__970994_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="objectinstance",
            index=models.Index(
                fields=["tree_id", "lft"], name="object_storage_objectinstaa702"
            ),
        ),
    ]
