# Generated by Django 4.2.23 on 2025-08-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "object_storage",
            "0002_remove_objectinstance_object_stor_parent__aead78_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttypedefinition",
            name="show_in_main_browser",
            field=models.BooleanField(
                default=True,
                help_text="Whether this object type appears in the main browser grid (False for sub-types only)",
            ),
        ),
    ]
