# Generated by Django 4.2.23 on 2025-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0003_add_show_in_main_browser"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttypedefinition",
            name="hierarchy_level",
            field=models.CharField(
                choices=[
                    ("top_level_only", "Top-level only"),
                    ("sub_object_only", "Sub-object only"),
                    ("both", "Both levels"),
                ],
                default="both",
                help_text="Where this object type can appear in the content hierarchy",
                max_length=20,
            ),
        ),
    ]
