# Generated by Django 4.2.23 on 2025-08-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0004_objecttypedefinition_hierarchy_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objecttypedefinition",
            name="show_in_main_browser",
        ),
    ]
