# Generated by Django 4.2.23 on 2025-08-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0005_remove_show_in_main_browser"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="objectinstance",
            name="object_stor_data_06e577_gin",
        ),
        migrations.RemoveIndex(
            model_name="objectinstance",
            name="object_stor_widgets_a9f3cd_gin",
        ),
        migrations.RemoveField(
            model_name="objectinstance",
            name="data",
        ),
        migrations.RemoveField(
            model_name="objectinstance",
            name="widgets",
        ),
        migrations.AddField(
            model_name="objectinstance",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The currently active version of this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_objects",
                to="object_storage.objectversion",
            ),
        ),
        migrations.AddIndex(
            model_name="objectinstance",
            index=models.Index(
                fields=["current_version"], name="object_stor_current_37364a_idx"
            ),
        ),
    ]
