# Generated by Django 4.2.23 on 2025-09-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0007_migrate_data_to_versions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="objectversion",
            name="unique_version_per_object",
        ),
        migrations.RemoveIndex(
            model_name="objectversion",
            name="object_stor_object__fe50a7_idx",
        ),
        migrations.RenameField(
            model_name="objectversion",
            old_name="object",
            new_name="object_instance",
        ),
        migrations.AddIndex(
            model_name="objectversion",
            index=models.Index(
                fields=["object_instance", "version_number"],
                name="object_stor_object__d6612d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectversion",
            constraint=models.UniqueConstraint(
                fields=("object_instance", "version_number"),
                name="unique_version_per_object",
            ),
        ),
    ]
