# Generated by Django 4.2.23 on 2025-09-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0029_add_html_elements_to_theme"),
        ("object_storage", "0008_fix_object_version_field_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttypedefinition",
            name="default_theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Default theme to apply when rendering objects of this type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="webpages.pagetheme",
            ),
        ),
    ]
