# Generated by Django 4.2.23 on 2025-09-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0009_add_default_theme_to_object_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objecttypedefinition",
            name="default_theme",
        ),
    ]
