# Generated by Django 4.2.23 on 2025-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0010_remove_default_theme_from_object_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectversion",
            name="effective_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When this version becomes active/published",
            ),
        ),
        migrations.AddField(
            model_name="objectversion",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When this version expires (null means never expires)",
            ),
        ),
        migrations.AddIndex(
            model_name="objectversion",
            index=models.Index(
                fields=["effective_date"], name="object_stor_effecti_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="objectversion",
            index=models.Index(fields=["expiry_date"], name="object_stor_expiry_idx"),
        ),
        migrations.AddIndex(
            model_name="objectversion",
            index=models.Index(
                fields=["effective_date", "expiry_date"],
                name="object_stor_date_range_idx",
            ),
        ),
    ]
