# Generated by Django 4.2.23 on 2025-09-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_alter_namespace_slug"),
        ("object_storage", "0012_migrate_publication_data_to_versions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="objectversion",
            name="object_stor_effecti_idx",
        ),
        migrations.RemoveIndex(
            model_name="objectversion",
            name="object_stor_expiry_idx",
        ),
        migrations.RemoveIndex(
            model_name="objectversion",
            name="object_stor_date_range_idx",
        ),
        migrations.AddField(
            model_name="objecttypedefinition",
            name="namespace",
            field=models.ForeignKey(
                blank=True,
                help_text="Namespace for organizing content and media for this object type",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="content.namespace",
            ),
        ),
        migrations.AddIndex(
            model_name="objecttypedefinition",
            index=models.Index(
                fields=["namespace"], name="object_stor_namespa_fc493c_idx"
            ),
        ),
    ]
