# Generated by Django 4.2.24 on 2025-10-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object_storage", "0014_objectversion_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectversion",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Mark this version as featured/pinned in listings",
            ),
        ),
    ]
