# Generated by Django 4.2.25 on 2025-10-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("object_storage", "0016_add_relationships"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="objectinstance",
            name="obj_inst_relationships_gin_idx",
        ),
        migrations.RemoveIndex(
            model_name="objectinstance",
            name="obj_inst_related_from_gin_idx",
        ),
    ]
