# Generated by Django 4.2.26 on 2025-12-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('object_storage', '0017_remove_objectinstance_obj_inst_relationships_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectinstance',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this object instance belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_instances', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='objectinstance',
            index=models.Index(fields=['tenant_id'], name='objectinstance_tenant_idx'),
        ),
    ]
