# Generated by Django 4.2.26 on 2025-12-15 20:00

from django.db import migrations
from django.contrib.auth.models import User


def assign_objects_to_default_tenant(apps, schema_editor):
    """Assign all existing object instances to the default tenant."""
    from django.db import connection
    import uuid
    
    Tenant = apps.get_model('core', 'Tenant')
    ObjectInstance = apps.get_model('object_storage', 'ObjectInstance')
    
    # Get or create default tenant
    default_tenant, created = Tenant.objects.get_or_create(
        identifier='default',
        defaults={
            'name': 'Default Tenant',
            'is_active': True,
            'created_by_id': User.objects.filter(is_superuser=True).first().id if User.objects.filter(is_superuser=True).exists() else User.objects.first().id if User.objects.exists() else None,
        }
    )
    
    if created:
        print(f"Created default tenant: {default_tenant.name} (identifier: {default_tenant.identifier})")
    else:
        print(f"Using existing default tenant: {default_tenant.name} (identifier: {default_tenant.identifier})")
    
    # Get tenant UUID as string
    tenant_uuid = str(default_tenant.id) if isinstance(default_tenant.id, uuid.UUID) else default_tenant.id
    
    # Assign all object instances without a tenant to the default tenant using raw SQL
    with connection.cursor() as cursor:
        cursor.execute(
            "UPDATE object_storage_objectinstance SET tenant_id = %s::uuid WHERE tenant_id IS NULL",
            [tenant_uuid]
        )
        objects_count = cursor.rowcount
    
    print(f"Assigned {objects_count} object instances to default tenant")


def reverse_migration(apps, schema_editor):
    """Reverse migration - set tenant to None for all object instances."""
    ObjectInstance = apps.get_model('object_storage', 'ObjectInstance')
    ObjectInstance.objects.all().update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('object_storage', '0018_add_tenant_to_storage_models'),
    ]

    operations = [
        migrations.RunPython(assign_objects_to_default_tenant, reverse_migration),
    ]

