# Generated by Django 4.2.26 on 2025-12-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_storage', '0019_assign_objects_to_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinstance',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this object instance belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='object_instances',
                to='core.tenant',
            ),
        ),
    ]

