# Generated by Django 4.2.24 on 2026-04-13 14:52

from django.db import migrations, models
import file_manager.storage


class Migration(migrations.Migration):
    dependencies = [
        ("object_storage", "0020_make_tenant_required_on_objectinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectinstance",
            name="related_from",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Reverse relationships (auto-maintained mirror of relationships field)",
            ),
        ),
        migrations.AlterField(
            model_name="objectinstance",
            name="relationships",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Many-to-many relationships to other objects with relationship types",
            ),
        ),
        migrations.AlterField(
            model_name="objecttypedefinition",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                help_text="Visual representation of this object type",
                null=True,
                storage=file_manager.storage.S3SystemStorage(),
                upload_to="object_types/icons/",
            ),
        ),
    ]
