# Generated by Django 4.2.30 on 2026-04-13 21:28

from django.db import migrations, models
import file_manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('object_storage', '0020_make_tenant_required_on_objectinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttypedefinition',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Visual representation of this object type', null=True, storage=file_manager.storage.S3SystemStorage(), upload_to='object_types/icons/'),
        ),
    ]
