# Generated by Django 4.2.24 on 2026-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("object_storage", "0021_alter_objecttypedefinition_icon_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectinstance",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional extensible properties for this object"
            ),
        ),
        migrations.AlterField(
            model_name="objecttypedefinition",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional extensible properties for this object type"
            ),
        ),
        migrations.AlterField(
            model_name="objecttypedefinition",
            name="schema",
            field=models.JSONField(
                blank=True, default=dict, help_text="JSON schema defining the fields for this object type"
            ),
        ),
        migrations.AlterField(
            model_name="objecttypedefinition",
            name="slot_configuration",
            field=models.JSONField(
                blank=True, default=dict, help_text="JSON configuration defining widget slots and restrictions"
            ),
        ),
        migrations.AlterField(
            model_name="objectversion",
            name="data",
            field=models.JSONField(blank=True, default=dict, help_text="Snapshot of object data at this version"),
        ),
        migrations.AlterField(
            model_name="objectversion",
            name="widgets",
            field=models.JSONField(
                blank=True, default=dict, help_text="Snapshot of widget configurations at this version"
            ),
        ),
    ]
