# Generated by Django 5.2.8 on 2026-10-09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_machine_api_key"),
        ("object_storage", "0025_objecttransferjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferCheckpoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("operation", models.CharField(choices=[("object_import", "Object import")], max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("restore_pending", "Restore pending"),
                            ("restoring", "Restoring"),
                            ("restored", "Restored"),
                            ("failed", "Failed"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("resource_scopes", models.JSONField(default=list)),
                ("snapshot", models.JSONField(default=dict)),
                ("created_resources", models.JSONField(blank=True, default=dict)),
                ("source_details", models.JSONField(blank=True, default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_transfer_checkpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restored_transfer_checkpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkpoint",
                        to="object_storage.objecttransferjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_checkpoints",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status", "created_at"], name="transfercp_tenant_idx")
                ],
            },
        ),
    ]
