# Generated by Django 4.2.25 on 2025-10-27 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0017_remove_all_deprecated_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="URL of the imported content", max_length=2000
                    ),
                ),
                (
                    "slot_name",
                    models.CharField(help_text="Target slot name", max_length=100),
                ),
                ("page_id", models.IntegerField(help_text="Target page ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[("append", "Append"), ("replace", "Replace")],
                        default="append",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("widgets_created", models.IntegerField(default=0)),
                ("media_files_imported", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Statistics about imported content (blocks, tables, images, files)",
                    ),
                ),
                (
                    "html_content",
                    models.TextField(
                        blank=True, help_text="Original HTML content that was imported"
                    ),
                ),
                (
                    "extracted_element_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Information about the extracted element",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        help_text="Namespace for imported media files",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.namespace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="content_imp_created_76a660_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="content_imp_status_b3a954_idx",
                    ),
                    models.Index(
                        fields=["page_id"], name="content_imp_page_id_8ca00e_idx"
                    ),
                ],
            },
        ),
    ]
