# Generated by Django 4.2.23 on 2025-08-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MediaThumbnail",
        ),
    ]
