# Generated by Django 4.2.23 on 2025-08-25 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0015_alter_tag_name_alter_tag_slug"),
        ("file_manager", "0002_remove_media_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.CharField(help_text="S3 key/path", max_length=500),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("content_type", models.CharField(max_length=100)),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA-256 hash for deduplication", max_length=64
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("archive", "Archive"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ai_generated_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="AI-suggested tags based on content analysis",
                    ),
                ),
                ("ai_suggested_title", models.CharField(blank=True, max_length=255)),
                (
                    "ai_extracted_text",
                    models.TextField(
                        blank=True,
                        help_text="Text extracted from images/documents via OCR",
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence score for suggestions (0.0-1.0)",
                        null=True,
                    ),
                ),
                (
                    "folder_path",
                    models.CharField(
                        blank=True, help_text="Target folder path", max_length=200
                    ),
                ),
                (
                    "upload_session_id",
                    models.CharField(
                        help_text="Session ID to group related uploads", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this temporary upload expires and should be cleaned up"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        help_text="Target namespace for final file",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.namespace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["upload_session_id"],
                        name="file_manage_upload__cbcfb7_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="file_manage_created_bc3151_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="file_manage_expires_e81de6_idx"
                    ),
                    models.Index(
                        fields=["file_hash"], name="file_manage_file_ha_0f0699_idx"
                    ),
                    models.Index(
                        fields=["namespace"], name="file_manage_namespa_a36abe_idx"
                    ),
                ],
            },
        ),
    ]
