# Generated by Django 4.2.23 on 2025-08-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0004_pendingmediafile_delete_temporaryupload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingmediafile",
            name="file_hash",
            field=models.CharField(
                help_text="SHA-256 hash for deduplication", max_length=64, unique=True
            ),
        ),
    ]
