# Generated by Django 4.2.23 on 2025-08-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0005_alter_pendingmediafile_file_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediacollection",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
