# Generated by Django 4.2.23 on 2025-09-18 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_manager", "0006_alter_mediacollection_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_media_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Soft delete flag"),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="last_referenced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="reference_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this file is referenced in content",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="referenced_in",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dictionary of content references {content_type: [ids]}",
            ),
        ),
    ]
