# Generated by Django 4.2.23 on 2025-09-18 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_manager", "0007_mediafile_deleted_at_mediafile_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="file_url",
            field=models.URLField(
                blank=True,
                help_text="Public URL for the file",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_media_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
