# Generated by Django 4.2.25 on 2025-10-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_mediafile_file_url_mediafile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='replaced_by',
            field=models.ForeignKey(blank=True, help_text='If this file was replaced, points to the replacement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_files', to='file_manager.mediafile'),
        ),
    ]
