# Generated by Django 4.2.26 on 2025-12-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('file_manager', '0010_mediafile_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this media file belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.tenant'),
        ),
    ]
