# Generated by Django 4.2.26 on 2025-12-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0012_assign_media_to_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this media file belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='media_files',
                to='core.tenant',
            ),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['tenant_id'], name='mediafile_tenant_idx'),
        ),
    ]

