# Generated by Django 4.2.24 on 2026-09-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('file_manager', '0013_make_tenant_required_on_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacollection',
            name='canonical_tags',
            field=models.ManyToManyField(blank=True, related_name='media_collections', to='taxonomy.tag'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='canonical_tags',
            field=models.ManyToManyField(blank=True, related_name='media_files', to='taxonomy.tag'),
        ),
    ]
