# Generated by Django 4.2.25 on 2025-10-28 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_tracking', '0002_seed_initial_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(db_index=True, help_text="Stable identifier for this prompt type (e.g., 'extract_page_metadata')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this prompt type does')),
                ('track_full_data', models.BooleanField(default=False, help_text='Store full prompt/response text in AIUsageLog entries')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to create AIUsageLog entries for this prompt type')),
                ('last_prompt', models.TextField(blank=True)),
                ('last_response', models.TextField(blank=True)),
                ('last_input_tokens', models.IntegerField(default=0)),
                ('last_output_tokens', models.IntegerField(default=0)),
                ('last_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('last_metadata', models.JSONField(blank=True, default=dict)),
                ('last_called_at', models.DateTimeField(blank=True, null=True)),
                ('last_duration_ms', models.IntegerField(blank=True, null=True)),
                ('total_calls', models.IntegerField(default=0, help_text='Total number of calls made')),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, help_text='Cumulative cost of all calls', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Prompt Configuration',
                'verbose_name_plural': 'AI Prompt Configurations',
                'ordering': ['prompt_type'],
            },
        ),
    ]
