# Generated by Django 4.2.30 on 2026-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tracking', '0004_aipromptconfig_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aibudgetalert',
            name='email_recipients',
            field=models.JSONField(blank=True, default=list, help_text='List of email addresses to notify'),
        ),
    ]
