# Generated by Django 4.2.27 on 2025-12-21 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('object_storage', '0020_make_tenant_required_on_objectinstance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('connection_type', models.CharField(choices=[('INTERNAL', 'Internal System'), ('EXTERNAL_REST', 'External REST API'), ('EXTERNAL_DB', 'External Database'), ('AGGREGATED', 'Aggregated Connection')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Connection configuration (e.g., base URL, credentials, DB params)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(help_text='Transformation mapping logic (mapping fields, aggregation rules)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('query_dsl', models.TextField(help_text='DSL or path for retrieving data')),
                ('output_type', models.CharField(choices=[('JSON', 'Simple JSON'), ('OBJECT_TYPE', 'Matching ObjectType')], default='JSON', max_length=20)),
                ('cache_ttl', models.PositiveIntegerField(default=3600, help_text='Cache TTL in seconds')),
                ('config', models.JSONField(default=dict, help_text='Stream specific configuration (e.g., paging rules, headers)')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='data_connections.dataconnection')),
                ('object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_storage.objecttypedefinition')),
                ('transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_connections.datatransformer')),
            ],
            options={
                'unique_together': {('connection', 'name')},
            },
        ),
    ]
