# Generated by Django 4.2.27 on 2025-12-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='workflow',
            field=models.JSONField(null=True, help_text='List of workflow actions to apply to each item'),
        ),
    ]
