# Generated by Django 4.2.27 on 2025-12-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connections', '0002_datastream_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='connection_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal System'), ('EXTERNAL_REST', 'External REST API'), ('EXTERNAL_DB', 'External Database')], max_length=20),
        ),
    ]
