# Generated by Django 4.2.27 on 2025-12-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_connections', '0003_alter_dataconnection_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='workflow',
            field=models.JSONField(blank=True, null=True, help_text='List of workflow actions to apply to each item'),
        ),
    ]
