# Generated by Django 4.2.24 on 2026-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_connections", "0004_alter_datastream_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataconnection",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Connection configuration (e.g., base URL, credentials, DB params)"
            ),
        ),
        migrations.AlterField(
            model_name="datastream",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Stream specific configuration (e.g., paging rules, headers)"
            ),
        ),
        migrations.AlterField(
            model_name="datatransformer",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Transformation mapping logic (mapping fields, aggregation rules)"
            ),
        ),
    ]
