# Generated by Django 4.2.27 on 2025-12-18 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(help_text='Unique identifier for the form', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Display name for the form', max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description of the form's purpose")),
                ('fields', models.JSONField(default=list, help_text='JSON list of form field definitions')),
                ('actions', models.JSONField(default=list, help_text='JSON list of actions to trigger on submission')),
                ('conditional_logic', models.JSONField(blank=True, default=dict, help_text='Declarative conditional logic rules')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional extensible properties')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this form belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='core.tenant')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text='The submitted form data')),
                ('metadata', models.JSONField(default=dict, help_text='Submission metadata (IP, user agent, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20)),
                ('processing_log', models.JSONField(blank=True, default=list, help_text='Log of action executions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['form', 'created_at'], name='forms_forms_form_id_e07f4f_idx'), models.Index(fields=['status'], name='forms_forms_status_fd1848_idx'), models.Index(fields=['tenant'], name='forms_forms_tenant__8d536d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['name'], name='forms_form_name_e0b326_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['is_active'], name='forms_form_is_acti_16c139_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['tenant'], name='forms_form_tenant__396bb1_idx'),
        ),
    ]
