# Generated by Django 4.2.27 on 2025-12-18 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(help_text='Unique identifier for the field type', max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_type', models.CharField(help_text='The underlying primitive field type', max_length=50)),
                ('config', models.JSONField(default=dict, help_text='Default configuration for this field type')),
                ('is_custom', models.BooleanField(default=True, help_text='True if created by admin, False if built-in')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_field_types', to='core.tenant')),
            ],
            options={
                'ordering': ['label'],
                'indexes': [models.Index(fields=['name'], name='forms_formf_name_9e8659_idx'), models.Index(fields=['is_active'], name='forms_formf_is_acti_8669f0_idx')],
            },
        ),
    ]
