# Generated by Django 4.2.26 on 2025-12-15 18:57

from django.db import migrations


def enable_rls_and_create_policies(apps, schema_editor):
    """Enable Row Level Security and create policies for tenant isolation."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Enable RLS on core_tenant table
        cursor.execute("ALTER TABLE core_tenant ENABLE ROW LEVEL SECURITY;")
        
        # Enable RLS on webpages_pagetheme table
        cursor.execute("ALTER TABLE webpages_pagetheme ENABLE ROW LEVEL SECURITY;")
        
        # Create policy for core_tenant (users can see all tenants for now)
        # In the future, this can be restricted based on user-tenant associations
        cursor.execute("""
            CREATE POLICY tenant_select_policy ON core_tenant
                FOR SELECT
                USING (true);
        """)
        
        cursor.execute("""
            CREATE POLICY tenant_insert_policy ON core_tenant
                FOR INSERT
                WITH CHECK (true);
        """)
        
        cursor.execute("""
            CREATE POLICY tenant_update_policy ON core_tenant
                FOR UPDATE
                USING (true);
        """)
        
        cursor.execute("""
            CREATE POLICY tenant_delete_policy ON core_tenant
                FOR DELETE
                USING (true);
        """)
        
        # Create policy for webpages_pagetheme (tenant isolation)
        cursor.execute("""
            CREATE POLICY pagetheme_tenant_isolation ON webpages_pagetheme
                FOR ALL
                USING (
                    tenant_id = current_setting('app.current_tenant_id', true)::uuid
                );
        """)
        
        print("Enabled RLS and created policies for tenant isolation")


def reverse_migration(apps, schema_editor):
    """Reverse migration - drop policies and disable RLS."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Drop policies
        cursor.execute("DROP POLICY IF EXISTS tenant_select_policy ON core_tenant;")
        cursor.execute("DROP POLICY IF EXISTS tenant_insert_policy ON core_tenant;")
        cursor.execute("DROP POLICY IF EXISTS tenant_update_policy ON core_tenant;")
        cursor.execute("DROP POLICY IF EXISTS tenant_delete_policy ON core_tenant;")
        cursor.execute("DROP POLICY IF EXISTS pagetheme_tenant_isolation ON webpages_pagetheme;")
        
        # Disable RLS
        cursor.execute("ALTER TABLE core_tenant DISABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE webpages_pagetheme DISABLE ROW LEVEL SECURITY;")
        
        print("Disabled RLS and dropped policies")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('webpages', '0062_make_tenant_required'),
    ]

    operations = [
        migrations.RunPython(enable_rls_and_create_policies, reverse_migration),
    ]
