# Generated by Django 4.2.26 on 2025-12-15 19:37

import uuid
from django.db import migrations, models
import django.db.models.deletion


def migrate_tenant_ids_to_uuid(apps, schema_editor):
    """Migrate tenant IDs from integer to UUID."""
    from django.db import connection
    
    Tenant = apps.get_model('core', 'Tenant')
    PageTheme = apps.get_model('webpages', 'PageTheme')
    
    with connection.cursor() as cursor:
        # Step 1: Drop RLS policy that depends on tenant_id
        cursor.execute("DROP POLICY IF EXISTS pagetheme_tenant_isolation ON webpages_pagetheme;")
        
        # Step 2: Create temporary UUID column in core_tenant
        cursor.execute("ALTER TABLE core_tenant ADD COLUMN id_new UUID;")
        
        # Step 3: Generate UUIDs for existing tenants and store mapping
        tenant_id_map = {}  # old_id -> new_uuid
        for tenant in Tenant.objects.all():
            new_uuid = uuid.uuid4()
            tenant_id_map[tenant.id] = str(new_uuid)
            cursor.execute(
                "UPDATE core_tenant SET id_new = %s WHERE id = %s",
                [str(new_uuid), tenant.id]
            )
        
        # Step 4: Drop foreign key constraint
        cursor.execute("ALTER TABLE webpages_pagetheme DROP CONSTRAINT IF EXISTS webpages_pagetheme_tenant_id_fkey;")
        
        # Step 5: Create temp UUID column in webpages_pagetheme
        cursor.execute("ALTER TABLE webpages_pagetheme ADD COLUMN tenant_id_new UUID;")
        
        # Step 6: Map old tenant_id values to new UUIDs
        for old_id, new_uuid in tenant_id_map.items():
            cursor.execute(
                "UPDATE webpages_pagetheme SET tenant_id_new = %s WHERE tenant_id = %s",
                [new_uuid, old_id]
            )
        
        # Step 7: Drop old tenant_id column and rename new one
        cursor.execute("ALTER TABLE webpages_pagetheme DROP COLUMN tenant_id;")
        cursor.execute("ALTER TABLE webpages_pagetheme RENAME COLUMN tenant_id_new TO tenant_id;")
        cursor.execute("ALTER TABLE webpages_pagetheme ALTER COLUMN tenant_id SET NOT NULL;")
        
        # Step 8: Drop old primary key constraint
        cursor.execute("ALTER TABLE core_tenant DROP CONSTRAINT IF EXISTS core_tenant_pkey;")
        
        # Step 9: Drop old id column
        cursor.execute("ALTER TABLE core_tenant DROP COLUMN id;")
        
        # Step 10: Rename new column to id
        cursor.execute("ALTER TABLE core_tenant RENAME COLUMN id_new TO id;")
        
        # Step 11: Make it primary key
        cursor.execute("ALTER TABLE core_tenant ADD PRIMARY KEY (id);")
        
        # Step 12: Recreate foreign key
        cursor.execute("""
            ALTER TABLE webpages_pagetheme 
            ADD CONSTRAINT webpages_pagetheme_tenant_id_fkey 
            FOREIGN KEY (tenant_id) REFERENCES core_tenant(id) ON DELETE CASCADE;
        """)
        
        # Step 13: Recreate RLS policy with UUID
        cursor.execute("""
            CREATE POLICY pagetheme_tenant_isolation ON webpages_pagetheme
                FOR ALL
                USING (
                    tenant_id = current_setting('app.current_tenant_id', true)::uuid
                );
        """)


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert UUID back to integer (not recommended, data loss possible)."""
    # This is complex and not recommended - would need to map UUIDs to sequential integers
    # For now, just raise an error
    raise NotImplementedError("Cannot reverse UUID migration - would cause data loss")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enable_rls'),
        ('webpages', '0062_make_tenant_required'),
    ]

    operations = [
        migrations.RunPython(migrate_tenant_ids_to_uuid, reverse_migration),
    ]
