# Generated by Django 4.2.26 on 2025-12-15 19:55

from django.db import migrations


def noop(apps, schema_editor):
    """No-op migration - tenant.id is already UUID from migration 0003."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_change_tenant_id_to_uuid'),
    ]

    operations = [
        # Note: tenant.id was already changed to UUID in migration 0003
        # This migration was auto-generated but is not needed
        migrations.RunPython(noop, migrations.RunPython.noop),
    ]
