# Generated by Django 4.2.26 on 2025-12-15 19:57

from django.db import migrations


def enable_rls_for_webpage(apps, schema_editor):
    """Enable Row Level Security and create policies for WebPage tenant isolation."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Enable RLS on webpages_webpage table
        cursor.execute("ALTER TABLE webpages_webpage ENABLE ROW LEVEL SECURITY;")
        
        # Create policy for webpages_webpage (tenant isolation)
        cursor.execute("""
            CREATE POLICY webpage_tenant_isolation ON webpages_webpage
                FOR ALL
                USING (
                    tenant_id = current_setting('app.current_tenant_id', true)::uuid
                );
        """)
        
        print("Enabled RLS and created policies for WebPage tenant isolation")


def reverse_migration(apps, schema_editor):
    """Reverse migration - drop policies and disable RLS."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Drop policy
        cursor.execute("DROP POLICY IF EXISTS webpage_tenant_isolation ON webpages_webpage;")
        
        # Disable RLS
        cursor.execute("ALTER TABLE webpages_webpage DISABLE ROW LEVEL SECURITY;")
        
        print("Disabled RLS and dropped policies for WebPage")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_tenant_to_webpage'),
        ('webpages', '0065_make_tenant_required_on_webpage'),
    ]

    operations = [
        migrations.RunPython(enable_rls_for_webpage, reverse_migration),
    ]

