# Generated by Django 4.2.26 on 2025-12-15 20:02

from django.db import migrations


def enable_rls_for_all_models(apps, schema_editor):
    """Enable Row Level Security and create policies for all tenant-associated tables."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Tables to enable RLS on
        tables = [
            'webpages_webpage',
            'content_namespace',
            'content_category',
            'content_tag',
            'object_storage_objectinstance',
            'file_manager_mediafile',
        ]
        
        # Enable RLS on all tables
        for table in tables:
            cursor.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
            print(f"Enabled RLS on {table}")
        
        # Create policies for each table
        policies = [
            ('webpages_webpage', 'webpage_tenant_isolation'),
            ('content_namespace', 'namespace_tenant_isolation'),
            ('content_category', 'category_tenant_isolation'),
            ('content_tag', 'tag_tenant_isolation'),
            ('object_storage_objectinstance', 'objectinstance_tenant_isolation'),
            ('file_manager_mediafile', 'mediafile_tenant_isolation'),
        ]
        
        for table, policy_name in policies:
            cursor.execute(f"""
                DROP POLICY IF EXISTS {policy_name} ON {table};
            """)
            cursor.execute(f"""
                CREATE POLICY {policy_name} ON {table}
                    FOR ALL
                    USING (
                        tenant_id = current_setting('app.current_tenant_id', true)::uuid
                    );
            """)
            print(f"Created policy {policy_name} on {table}")
        
        print("Enabled RLS and created policies for all tenant-associated tables")


def reverse_migration(apps, schema_editor):
    """Reverse migration - drop policies and disable RLS."""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Drop policies
        policies = [
            ('webpages_webpage', 'webpage_tenant_isolation'),
            ('content_namespace', 'namespace_tenant_isolation'),
            ('content_category', 'category_tenant_isolation'),
            ('content_tag', 'tag_tenant_isolation'),
            ('object_storage_objectinstance', 'objectinstance_tenant_isolation'),
            ('file_manager_mediafile', 'mediafile_tenant_isolation'),
        ]
        
        for table, policy_name in policies:
            cursor.execute(f"DROP POLICY IF EXISTS {policy_name} ON {table};")
        
        # Disable RLS
        tables = [
            'webpages_webpage',
            'content_namespace',
            'content_category',
            'content_tag',
            'object_storage_objectinstance',
            'file_manager_mediafile',
        ]
        
        for table in tables:
            cursor.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
        
        print("Disabled RLS and dropped policies for all tenant-associated tables")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enable_rls_for_webpage'),
        ('webpages', '0065_make_tenant_required_on_webpage'),
        ('content', '0020_make_tenant_required_on_content'),
        ('object_storage', '0020_make_tenant_required_on_objectinstance'),
        ('file_manager', '0013_make_tenant_required_on_mediafile'),
    ]

    operations = [
        migrations.RunPython(enable_rls_for_all_models, reverse_migration),
    ]

